### ISSUE TITLE
Just tried from mac 10.11.6 with latest Java

### ISSUE THREAD

**Issue by tspannhw** [jfrazee/nifi-processor-bundle-scala.g8#1]
➜  projects g8 jfrazee/nifi-processor-bundle.g8
The authenticity of host 'github.com' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting?: yes
org.eclipse.jgit.api.errors.JGitInternalException: Invalid remote: origin

**Comment by jfrazee** [comment]
@tspannhw I think maybe you specified the repo wrong it's `jfrazee/nifi-processor-bundle-scala.g8` not `jfrazee/nifi-processor-bundle.g8`.

**Comment by tspannhw** [comment]
Thanks that worked.

You need to update the docs

Basic Usage

To get started using the template:

brew install giter8
g8 jfrazee/nifi-**processor**-bundle.g8
cd [NAME] && mvn compile test package
